# SonarQube 서버에서 이 프로젝트를 식별할 고유 키 (원하는 영문/숫자로 작성)
sonar.projectKey=cl_embed

# 대시보드에 표시될 프로젝트 이름
sonar.projectName=cl_embed

# 소스 코드 분석 디렉토리 (docker/, docs/ 하위는 분석 불필요)
sonar.sources=nextjs, laravel

# 인코딩 설정
sonar.sourceEncoding=UTF-8

# (선택/권장) 분석에서 제외할 폴더 지정
sonar.exclusions=vendor/**, node_modules/**, .next/**