networks:
  docker_public_1:
    external: true
  docker_private_1:
    external: true

services:

  cl_embed_nextjs:
    container_name: cl_embed_nextjs
    hostname: 'cl_embed_nextjs'
    build:
      context: ../nextjs
      dockerfile: dockerfile
    restart: unless-stopped
    environment:
      WATCHPACK_POLLING: true  # 파일 변경 즉시 감지 (HMR)
      NODE_ENV: development
      PORT: 3000
      TZ: Asia/Seoul
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ../nextjs:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - docker_public_1
      - docker_private_1
    # depends_on:
    #   - cl_embed_laravel
    #   - pgvector_03
    #   - redis_04

  cl_embed_laravel:  # 8.5.5-fpm-trixie
    container_name: cl_embed_laravel
    hostname: 'cl_embed_laravel'
    build:
      context: ./laravel
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - ../laravel:/var/www/html
      - ./laravel/volume/log:/var/log/php
    environment:
      TZ: ${TZ}
    expose:
      - "8000"
      - "8080"
      # - "9000"
    networks:
      - docker_public_1
      - docker_private_1

