networks:
  docker_public_1:
    external: true
  docker_private_1:
    external: true

services:

  cl_embed_nextjs:
    container_name: cl_embed_nextjs
    hostname: 'cl_embed_nextjs'
    build:
      context: ../nextjs
      dockerfile: ../docker/nextjs/dockerfile
    restart: unless-stopped
    environment:
      WATCHPACK_POLLING: true  # 파일 변경 즉시 감지 (HMR)
      PORT: 3000
      TZ: Asia/Seoul
    # ports:
    #   - "3000:3000"
    expose:
      - "3000"
    volumes:
      - ../nextjs:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - docker_public_1
      - docker_private_1

  cl_embed_laravel:  # 8.5.5-fpm-trixie
    container_name: cl_embed_laravel
    hostname: 'cl_embed_laravel'
    build:
      context: ./laravel
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - ../laravel:/var/www/html
      # - ./laravel/volume/log:/var/log/php
    environment:
      TZ: ${TZ}
    expose:
      - "8000"
      - "8080"
      # - "9000"
    networks:
      - docker_public_1
      - docker_private_1

  cl_embed_swagger:
    image: swaggerapi/swagger-ui:latest
    container_name: cl_embed_swagger
    hostname: 'cl_embed_swagger'
    restart: unless-stopped
    # volumes:
    #   - ..:/swagger:ro
    environment:
      BASE_URL: "/swagger"
      URLS: "[
        { url: '/api/documentation', name: 'Laravel API' },
        { url: '/docs/next-spec.json', name: 'Next.js API' }
      ]"
      TZ: ${TZ}
    expose:
      - "8080"
    networks:
      - docker_public_1
      - docker_private_1
