server {
    listen 80;
    server_name localhost;

    error_log  docker/nginx/volume/log/embed_error.log;
    access_log docker/nginx/volume/log/embed_access.log json_log;

    # 1. 백엔드 API 라우팅 (Laravel)
    # /api 로 시작하는 모든 요청은 Laravel 컨테이너로 보냅니다.
    location /api/ {
        include conf.d/common/proxy.conf;
        proxy_pass http://cl_embed_laravel:8000;
        error_log  docker/nginx/volume/log/embed_api_error.log;
        access_log docker/nginx/volume/log/embed_api_access.log json_log;
    }

    # 2. WebSocket 라우팅 (Laravel Reverb)
    # Reverb가 사용하는 특정 경로(예: /app)를 WebSocket으로 연결합니다.
    location /app/ {
        include conf.d/common/proxy.conf;
        proxy_http_version 1.1;
        proxy_pass http://cl_embed_laravel:8080;
        error_log  docker/nginx/volume/log/embed_app_error.log;
        access_log docker/nginx/volume/log/embed_app_access.log json_log;
    }

    # 3. Swagger UI
    location /swagger/ {
        include conf.d/common/proxy.conf;
        proxy_http_version 1.1;
        proxy_pass http://cl_embed_swagger:8080;
        error_log  docker/nginx/volume/log/embed_swagger_error.log;
        access_log docker/nginx/volume/log/embed_swagger_access.log json_log;
    }

    # 4. 프론트엔드 라우팅 (Next.js)
    # 위에서 걸러지지 않은 나머지 모든 요청은 Next.js로 보냅니다.
    location / {
        include conf.d/common/proxy.conf;
        proxy_http_version 1.1;
        proxy_pass http://cl_embed_nextjs:3000;
        error_log  docker/nginx/volume/log/embed_nextjs_error.log;
        access_log docker/nginx/volume/log/embed_nextjs_access.log json_log;
    }
}